identifier_name:
  min_length: 1
  max_length: 50
  allowed_symbols: "_"

# line_length:
#  warning: 200
#  error: 300
#  ignores_comments: true
#  ignores_urls: true

large_tuple:
  warning: 4
  error: 5

disabled_rules:
  - todo
  - for_where
  - file_length
  - force_cast
  - force_try
  - cyclomatic_complexity
  - generic_type_name
  - function_body_length
  - type_body_length
  - function_parameter_count
  - line_length
  - operator_whitespace
  - nesting
  - class_delegate_protocol

excluded:
  - ".build"
  - ".git"
  - ".swiftpm"
  - ".claude"
  - Modules/*/.build/
  - Modules/Secrets/Sources/Secrets/SecretKey.swift
  - Modules/Account/Tests/
  - Modules/Account/Sources/Account/Feedly/
  - Widget/Resources/Localized.swift
  - Shared/Extensions/NSAttributedString+NetNewsWire.swift
  - buildscripts/


