#!/bin/sh

rm -rf ~/.build
mkdir ~/.build

rm ~/Desktop/Evergreen$1.zip
rm -rf ~/Desktop/Evergreen.app

xcodebuild -workspace Evergreen.xcworkspace -scheme "Evergreen" -derivedDataPath ~/.build -configuration Release 

ditto /Users/brent/.build/Build/Products/Release/Evergreen.app ~/Desktop/Evergreen.app
open ~/Desktop

pushd ~/Desktop

zip --symlinks -r "Evergreen$1.zip" "Evergreen.app/"
ditto Evergreen$1.zip ~/Archive/Releases/

popd
