// Generated by SecretKey.swift.gyb
import Foundation

public struct SecretKey {

  public static let mercuryClientID: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()

  public static let mercuryClientSecret: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()

  public static let feedlyClientID: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()

  public static let feedlyClientSecret: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()

  public static let inoreaderAppID: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()

  public static let inoreaderAppKey: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()
}

private let salt: [UInt8] = [
  0x90, 0x43, 0xe3, 0x10, 0x4a, 0x75, 0xdc, 0xe0, 
  0x9b, 0x4c, 0xf0, 0xc0, 0x99, 0x22, 0x0a, 0x5d, 
  0x50, 0xa8, 0xe4, 0x6c, 0x87, 0x95, 0x67, 0x87, 
  0x0a, 0x07, 0xf8, 0x63, 0x90, 0xcf, 0x92, 0x91, 
  0x4c, 0x80, 0x1c, 0xf5, 0xd5, 0xdd, 0x8a, 0x34, 
  0xf2, 0xfd, 0xfb, 0x4c, 0x94, 0x9b, 0x36, 0x97, 
  0x0d, 0x80, 0x2b, 0xfd, 0x9a, 0xaf, 0x83, 0x96, 
  0x60, 0x1a, 0xae, 0xd8, 0xf5, 0xed, 0x1c, 0x1d, 
]

private func decode(_ encoded: [UInt8]) -> String {
  String(decoding: encoded.enumerated().map { (offset, element) in
      element ^ salt[offset % salt.count]
  }, as: UTF8.self)
}
